function cellDensities = ImportCellAtlas(numberOrDensity)
%% Import data from text file.
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/30 16:02:52

if nargin < 1
    numberOrDensity = 'density';
end

%% Initialize variables.
switch numberOrDensity
case 'number'
    fileName = 'Data_Sheet_1_Cell_Atlas_for_Mouse_Brain.csv';
case 'density'
    fileName = 'Data_Sheet_2_Cell_Atlas_for_Mouse_Brain.csv';
end
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(fileName,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
cellDensities = table(dataArray{1:end-1}, 'VariableNames', {'regionName','cells','neurons','glia','excitatory','inhibitory','modulatory','astrocytes','oligodendrocytes','microglia'});

end
