function geneAcronyms = ImportBrainGenes(doProcess)
%-------------------------------------------------------------------------------
% A list of brain genes from GXD [Finger:2017hy]
%-------------------------------------------------------------------------------
if nargin < 1
    doProcess = false;
end
%-------------------------------------------------------------------------------
if doProcess
    %% Import data from text file.
    % Script for importing data from the following text file:
    %
    %    /Users/benfulcher/GoogleDrive/Work/CurrentProjects/CellTypesMouse/Code/Data/MGIgeneExpressionQuery_20171115_001530.txt
    %
    % To extend the code to different selected data or a different text file,
    % generate a function instead of a script.

    % Auto-generated by MATLAB on 2017/11/15 17:01:50

    %% Initialize variables.
    fprintf(1,'Reading from brain-related genes flagged in GXD\n');
    filename = 'MGIgeneExpressionQuery_20171115_001530.txt';
    delimiter = '\t';
    startRow = 2;

    %% Format for each line of text:
    %   column2: text (%s)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%*s%s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

    %% Open the text file.
    fileID = fopen(filename,'r');

    %% Read columns of data according to the format.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

    %% Close the text file.
    fclose(fileID);

    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for
    % unimportable data, select unimportable cells in a file and regenerate the
    % script.

    %% Create output variable
    geneAcronymsAll = [dataArray{1:end-1}];
    geneAcronyms = unique(geneAcronymsAll);

    % Export
    fileOut = fullfile('Data','GXDBrainGenes.mat');
    save(fileOut,'geneAcronyms')
else
    fileOut = fullfile('Data','GXDBrainGenes.mat');
    load(fileOut,'geneAcronyms')
end

fprintf(1,'Loaded a set of %u brain-expressed genes from GXD\n',length(geneAcronyms));

end
