function cellDensities = ImportCellDensities()
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/benfulcher/GoogleDrive/Work/CurrentProjects/Timescales_Wang/Code/Data/cellDensities.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/10/21 11:24:35

%% Import the data
[~, ~, raw] = xlsread('CellDensities.xlsx','Sheet1');
raw = raw(3:820,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2]);
raw = raw(:,[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
cellDensities = table;

%% Allocate imported array to column variable names
cellDensities.acronym = cellVectors(:,1);
cellDensities.name = cellVectors(:,2);
cellDensities.structureOrder = data(:,1);
cellDensities.PV_mean = data(:,2);
cellDensities.PV_std = data(:,3);
cellDensities.SST_mean = data(:,4);
cellDensities.SST_std = data(:,5);
cellDensities.VIP_mean = data(:,6);
cellDensities.VIP_std = data(:,7);
cellDensities.SST_CR_mean = data(:,8);
cellDensities.SST_CR_std = data(:,9);
cellDensities.SST_nNOS_mean = data(:,10);
cellDensities.SST_nNOS_std = data(:,11);
cellDensities.VIP_CR_mean = data(:,12);
cellDensities.VIP_CR_std = data(:,13);
cellDensities.VIP_CCK_mean = data(:,14);
cellDensities.VIP_CCK_std = data(:,15);

% Add some extras:
cellDensities.PV_SST_ratio = cellDensities.PV_mean./cellDensities.SST_mean;
cellDensities.PV_PV_SST_ratio = cellDensities.PV_mean./(cellDensities.PV_mean + cellDensities.SST_mean);

% Add Isocortex division label for compatibility...:
cellDensities.divisionLabel = arrayfun(@(x)sprintf('Isocortex'),1:height(cellDensities),'UniformOutput',false)';

end
